import NewTicketPage from "@/components/templates/dashboard/NewTicketPage";

export const metadata = {
  title: "ivco new ticket",
  description: "Generated by create next app",
};

function page() {
  return <NewTicketPage />;
}

export default page;
