//templates
import GenealogyPage from "@/components/templates/dashboard/GenealogyPage";

export const metadata = {
  title: "ivco Genealogy",
  description: "Generated by create next app",
};

function page() {
  return <GenealogyPage />;
}

export default page;
