//templates
import TopupPage from "@/components/templates/dashboard/TopupPage";

export const metadata = {
  title: "ivco Top Up",
  description: "Generated by create next app",
};

function page() {
  return <TopupPage />;
}

export default page;
