//templates
import WithDrawalPage from "@/components/templates/dashboard/WithDrawalPage";

export const metadata = {
  title: "ivco Withdrawal",
  description: "Generated by create next app",
};

function page() {
  return <WithDrawalPage />;
}

export default page;
