//templates
import OwnerShipPage from "@/components/templates/dashboard/OwnerShipPage";

export const metadata = {
  title: "ivco Ownership",
  description: "Generated by create next app",
};

function page() {
  return <OwnerShipPage />;
}

export default page;
