//styles
import "./globals.css";

//fonts
import { Irancell } from "@/utils/Fonts";
import NextAuthProvider from "@/providers/NextAuthProvider";
import Layout from "@/components/layouts/Layout";

export const metadata = {
  title: "ivco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <NextAuthProvider>
        <Layout>
          <div className={Irancell.className}>{children}</div>
        </Layout>
      </NextAuthProvider>
    </html>
  );
}
