//styles
import Layout from "@/components/layouts/Layout";
import "./globals.css";

//fonts
import { Irancell } from "@/utils/Fonts";

export const metadata = {
  title: "iwco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <Layout>
        <body className={Irancell.className}>{children}</body>
      </Layout>
    </html>
  );
}
