import "./globals.css";

import { Irancell } from "@/utils/Fonts";

export const metadata = {
  title: "iwco",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr">
      <body className={Irancell.className}>{children}</body>
    </html>
  );
}
