//templates
import CommissionsPage from "@/components/templates/dashboard/CommissionsPage";

export const metadata = {
  title: "ivco Commissions",
  description: "Generated by create next app",
};

function page() {
  return <CommissionsPage />;
}

export default page;
