//templates
import SupportPage from "@/components/templates/dashboard/SupportPage";

export const metadata = {
  title: "ivco Support",
  description: "Generated by create next app",
};

function page() {
  return <SupportPage />;
}

export default page;
