//template
import MainPage from "@/components/templates/dashboard/MainPage";

export const metadata = {
  title: "ivco dashboard",
  description: "Generated by create next app",
};

function page() {
  return <MainPage />;
}

export default page;
