//templates
import WalletPage from "@/components/templates/dashboard/WalletPage";

export const metadata = {
  title: "ivco Wallet",
  description: "Generated by create next app",
};

function page() {
  return <WalletPage />;
}

export default page;
